### ISSUE TITLE
Exception: Error while deserializing header: HeaderTooLarge

### ISSUE THREAD

**Issue by truedat101** [PKU-YuanGroup/MagicTime#21]
Header to large error when running example.  I suspect this is a problem with how I downloaded the models when running prep scripts.  Will retry from scratch.

```
11:32 $ python inference_magictime.py --config sample_configs/RealisticVision.yaml
The results will be save to outputs/RealisticVision-3
Use MagicAdapter-S
Use MagicAdapter-T
Use Magic_Text_Encoder
Traceback (most recent call last):
  File "myhome/dev/repos/MagicTime/inference_magictime.py", line 249, in <module>
    main(args)
  File "myhome/tools/miniforge3/envs/magictime/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/dkords/dev/repos/MagicTime/inference_magictime.py", line 61, in main
    text_encoder = CLIPTextModel.from_pretrained(model_config.pretrained_model_path, subfolder="text_encoder").cuda()
  File "myhome//tools/miniforge3/envs/magictime/lib/python3.10/site-packages/transformers/modeling_utils.py", line 3284, in from_pretrained
    with safe_open(resolved_archive_file, framework="pt") as f:
safetensors_rust.SafetensorError: Error while deserializing header: HeaderTooLarge
```

**Comment by truedat101** [comment]
Verified: https://huggingface.co/runwayml/stable-diffusion-v1-5/tree/main/text_encoder

seems to not download properly on my linux ubuntu 22.04.  File sizes are wrong.  Short investigation indicates HeaderTooLarge error is likely a problem with git-lfs missing or the actual large blobs not downloading.

This is due to a system misconfiguration in my case.  git lfs install command by itself doesn't seem to work.  Further investigation yields some questions about the correct way to actually install git lfs.  Will attempt to just install via package manager.

**Comment by truedat101** [comment]
Resolved with proper git-lfs installation before running clone.
